
  | Name      | Type          | Params
--------------------------------------------
0 | criterion | CTCLoss       | 0     
1 | wav2vec2  | Wav2Vec2Model | 315 M 
2 | lm_head   | Linear        | 49.2 K
3 | val_per   | PER           | 0     
4 | test_per  | PER           | 0     
--------------------------------------------
311 M     Trainable params
4.2 M     Non-trainable params
315 M     Total params
1,261.952 Total estimated model params size (MB)
[INFO] 
  | Name      | Type          | Params
--------------------------------------------
0 | criterion | CTCLoss       | 0     
1 | wav2vec2  | Wav2Vec2Model | 315 M 
2 | lm_head   | Linear        | 49.2 K
3 | val_per   | PER           | 0     
4 | test_per  | PER           | 0     
--------------------------------------------
311 M     Trainable params
4.2 M     Non-trainable params
315 M     Total params
1,261.952 Total estimated model params size (MB)
/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/distributed.py:51: UserWarning: The dataloader, val dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 4 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  warnings.warn(*args, **kwargs)
/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/distributed.py:51: UserWarning: The dataloader, train dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 4 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  warnings.warn(*args, **kwargs)

/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/distributed.py:51: UserWarning: The dataloader, test dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 4 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  warnings.warn(*args, **kwargs)
Mon Mar 22 10:58:52 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.56       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P0    39W / 300W |   7041MiB / 16160MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
rm: cannot remove 'self-supervised-speech': No such file or directory
ASR_project.ipynb		metrics.py    self-unsupervised-low-res-speech
ASR_project_minimum_code.ipynb	phonemize.py  wandb
data				__pycache__
dataloader.py			README.md
[autoreload of dataloader failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/IPython/extensions/autoreload.py", line 247, in check
    superreload(m, reload, self.old_objects)
ValueError: prepare_data() requires a code object with 1 free vars, not 0
]
